spring:
  profiles:
    active: development
---
spring:
  profiles: development
  cloud:
    stream:
      bindings:
        output:
          destination: payment
          contentType: 'application/json'
  redis:
    host: localhost
    port: 6379
server:
  port: 0
events:
  worker: http://payment-worker/v1/events
---
spring:
  profiles: test
  cloud:
    stream:
      bindings:
        output:
          destination: payment
          contentType: 'application/json'
server:
  port: 0
events:
  worker: http://payment-worker/v1/events
eureka:
  client:
    enabled: false