spring:
  profiles:
    active: development
---
spring:
  profiles: development
  jackson:
    default-property-inclusion: non_null
  cloud:
    stream:
      bindings:
        output:
          destination: account
          contentType: 'application/json'
server:
  port: 0
events:
  worker: http://account-worker/v1/events
---
spring:
  profiles: test
  cloud:
    stream:
      bindings:
        output:
          destination: account
          contentType: 'application/json'
server:
  port: 0
events:
  worker: http://account-worker/v1/events
eureka:
  client:
    enabled: false