language: java
jdk:
- oraclejdk8
services:
- redis
- docker
install: mvn clean install -DskipDockerBuild
before_install:
- docker pull spotify/kafka
- docker run -d -p 2181:2181 -p 9092:9092 spotify/kafka