spring:
  profiles:
    active: development
---
spring:
  profiles: development
  cloud:
    stream:
      bindings:
        warehouse:
          destination: warehouse
          contentType: 'application/json'
        reservation:
          destination: reservation
          contentType: 'application/json'
        inventory:
          destination: inventory
          contentType: 'application/json'
server:
  port: 0
events:
  worker: http://warehouse-worker/v1/events
---
spring:
  profiles: test
  cloud:
    stream:
      bindings:
        output:
          destination: warehouse
          contentType: 'application/json'
server:
  port: 0
events:
  worker: http://warehouse-worker/v1/events
eureka:
  client:
    enabled: false
---
spring:
  profiles: cloud
  cloud:
    stream:
      bindings:
        output:
          destination: warehouse
          contentType: 'application/json'
events:
  worker: http://warehouse-worker/v1/events
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePort: 80
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    leaseRenewalIntervalInSeconds: 5
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${vcap.services.discovery-service.credentials.uri:http://localhost:8761}/eureka/