spring:
  profiles:
    active: development
---
spring:
  profiles: development
  cloud:
    stream:
      bindings:
        input:
          destination: account
          group: account-group
          contentType: 'application/json'
          consumer:
            durableSubscription: true
server:
  port: 0