spring:
  profiles:
    active: development
---
spring:
  profiles: development
  cloud:
    stream:
      bindings:
        input:
          destination: order
          group: order-group
          contentType: 'application/json'
          consumer:
            durableSubscription: true
  jackson:
    default-property-inclusion: non_null
server:
  port: 0
amazon:
  aws:
    access-key-id: replace
    access-key-secret: replace
---
spring:
  profiles: test
eureka:
  client:
    enabled: false
server:
  port: 0
---
spring:
  profiles: cloud
  cloud:
    stream:
      bindings:
        input:
          destination: order
          group: order-group
          contentType: 'application/json'
          consumer:
            durableSubscription: true
server:
  port: 0
amazon:
  aws:
    access-key-id: replace
    access-key-secret: replace
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePort: 80
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    leaseRenewalIntervalInSeconds: 5
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${vcap.services.discovery-service.credentials.uri:http://localhost:8761}/eureka/