spring:
  profiles:
    active: development
server:
  port: 0
amazon:
  aws:
    access-key-id: replace
    access-key-secret: replace
---
spring:
  profiles: development
  cloud:
    stream:
      bindings:
        input:
          contentType: 'application/json'
          destination: payment
          group: payment-group
          consumer:
            durableSubscription: true
---
spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${DOCKER_IP:192.168.99.100}
          zk-nodes: ${DOCKER_IP:192.168.99.100}
      bindings:
        input:
          contentType: 'application/json'
          destination: payment
          group: payment-group
          consumer:
            durableSubscription: true
          concurrency: 20
eureka:
  client:
    service-url:
      defaultZone: http://${DOCKER_IP:192.168.99.100}:8761/eureka
    registryFetchIntervalSeconds: 5
  instance:
    hostname: ${DOCKER_IP:192.168.99.100}
    instance-id: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 5
---
spring:
  profiles: test
eureka:
  client:
    enabled: false
logging:
  level:
    org:
      apache:
        zookeeper:
          ZooKeeper: error
    org.apache.kafka.clients.producer.ProducerConfig: error
---
spring:
  profiles: cloud
  cloud:
    stream:
      bindings:
        input:
          contentType: 'application/json'
          destination: payment
          group: payment-group
          consumer:
            durableSubscription: true
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePort: 80
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    leaseRenewalIntervalInSeconds: 5
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${vcap.services.discovery-service.credentials.uri:http://localhost:8761}/eureka/