spring:
  profiles:
    active: development
---
spring:
  profiles: development
  cloud:
    stream:
      bindings:
        output:
          destination: order
          contentType: 'application/json'
server:
  port: 0
events:
  worker: http://order-worker/v1/events
---
spring:
  profiles: test
  cloud:
    stream:
      bindings:
        output:
          destination: order
          contentType: 'application/json'
server:
  port: 0
events:
  worker: http://order-worker/v1/events
eureka:
  client:
    enabled: false